### ISSUE TITLE
Celery schedule

### ISSUE THREAD

**Issue by dhvcc** [Sora-reader/backend#15]
Нужно добавить поддержку [Celery](https://docs.celeryproject.org/en/stable/django/first-steps-with-django.html) и сделать ежедневную таску, на запуск парсинга основных данных

Необходимо обновить композ, добавить туда `redis` и `celery` контейнеры

**Comment by ScriptHound** [comment]
![image](https://user-images.githubusercontent.com/24416779/113538820-e1e69800-95e4-11eb-8bbd-2247da932d72.png)
Контейнер Celery давно депрекейтед

**Comment by dhvcc** [comment]
> ![image](https://user-images.githubusercontent.com/24416779/113538820-e1e69800-95e4-11eb-8bbd-2247da932d72.png)
> Контейнер Celery давно депрекейтед https://hub.docker.com/_/celery

Это значит смену интерфейса, а не объявление подхода через докер депрекейтед
