### ISSUE TITLE
On demand detail parsing

### ISSUE THREAD

**Issue by dhvcc** [Sora-reader/backend#16]
Необходимо реализовать функционал позволяющий получить список глав манги с ссылками на них, и, наверное, ещё какую-то инфу

И функцию проверки - если данных нет, или если обновлялись больше, чем 1 час назад (`datetime.now()` и `updated`), нужно спарсить эту мангу и обновить данные в БД

**Comment by ScriptHound** [comment]
В детальном парсинге у некоторых тайтлов есть поле категория, как тут - https://readmanga.live/ia_zloi_bog
Также не везде есть автор, и вместо него могут быть художник и сценарист, как в вышеупомянутой манге. Для наглядности, манга, у которой есть автор - https://readmanga.live/naruto__A1ec180

**Comment by dhvcc** [comment]
Тогда новый `М2М` с художником, а категориию как `TextField` с дефолтным значением `manga`
