### ISSUE TITLE
JWT

### ISSUE THREAD

**Issue by dhvcc** [Sora-reader/backend#21]
Нужно реализовать нормальную работу `JWT`
Нужны эндпоинты:
1. Авторизация и получение токена (access+refresh) `/api/token/auth`
2. Валидация токена `/api/token/verify`
3. Обновление токена `/api/token/refresh`
4. Регистрация пользователя и получение токена сразу `/api/sign-up/`

Так же нужно убрать поддержку `TokenAuthentication` и оставить только `Session`/`JWT`

**Comment by dhvcc** [comment]
@NikDark можешь взять этот тикет?

**Comment by NikDark** [comment]
> @NikDark можешь взять этот тикет?

Конечно
