### ISSUE TITLE
Search

### ISSUE THREAD

**Issue by dhvcc** [Sora-reader/backend#32]
Нужен эндпоинт для поиска манги по нашей базе. Скорее всего нужно использовать `ILIKE` или что-то такое для частичного совпадения. Так же нужно не забыть про префетч, что бы не тормозить `SQL`

Это всё используя `DRF`, конечно

**Comment by yurylahodzich** [comment]
Сделаю через elasticSearch

**Comment by dhvcc** [comment]
> Сделаю через elasticSearch

А что по прайсу сервиса?

**Comment by yurylahodzich** [comment]
за него платить разве надо?

**Comment by yurylahodzich** [comment]
Там опенсорс версия есть и basic  они бесплатные

**Comment by dhvcc** [comment]
> за него платить разве надо?

Я думал ты авс хотел подключить, извиняюсь

**Comment by dhvcc** [comment]
Заблочено до схемы из #56

**Comment by dhvcc** [comment]
По сути, эластик не нужен, достаточно текущего поиска
