### ISSUE TITLE
Chapter link

### ISSUE THREAD

**Issue by dhvcc** [Sora-reader/backend#47]
Нужно провести ресерч того, как будем доставать саму ссылку на главу

- Какие виды картинок бывают (полная глава/часть главы/???)
- По каким ссылкам находятся?
- Есть защита/авторизация?
- ...

**Comment by ScriptHound** [comment]
`<img class="manga-img_0" data-page="0" src="https://t7.mangas.rocks/auto/28/62/51/01_fan-naruto.ru.png" rh="1100" rw="684" id="mangaPicture" pagenum="0" width="684" height="1100">`
Ссылки находятся здесь, что для манхвы, что для манги. 

Ссылки на страницы главы условно начинаются с 0, потому что второй странице главы будет соответствовать эта ссылка
`https://readmanga.live/naruto__A1ec180/vol0/1#page=1`

**Comment by dhvcc** [comment]
> `<img class="manga-img_0" data-page="0" src="https://t7.mangas.rocks/auto/28/62/51/01_fan-naruto.ru.png" rh="1100" rw="684" id="mangaPicture" pagenum="0" width="684" height="1100">`
> Ссылки находятся здесь, что для манхвы, что для манги. 
> 
> Ссылки на страницы главы условно начинаются с 0, потому что второй странице главы будет соответствовать эта ссылка
> `https://readmanga.live/naruto__A1ec180/vol0/1#page=1`

Вот хотелось бы понимать закономерность получения именно ссылки из <img/>, что бы не добавлять на каждую главу +1 запрос и парсинг
Там не только 1 сервер статиков

**Comment by dhvcc** [comment]
Выбрал пару разлиных манг, итого формат такой

Выбрал пару разлиных манг, итого формат такой

_Клинок_
Томы/главы - /vol1/1
Страницы - #page=1:
- https://t6.mangas.rocks/auto/27/35/89/002.png_res.jpg
- https://t7.mangas.rocks/auto/27/35/89/003.png_res.jpg
- https://t7.mangas.rocks/auto/27/35/89/004.png_res.jpg
- https://t6.mangas.rocks/auto/27/35/89/005.png_res.jpg

_Наруто_
Томы/главы - vol0/1
Страницы - #page=2:
- https://t7.mangas.rocks/auto/28/62/51/03_fan-naruto.ru.png
- https://t7.mangas.rocks/auto/28/62/51/04_fan-naruto.ru.png
- https://t7.mangas.rocks/auto/28/62/51/05_fan-naruto.ru.png
- https://t6.mangas.rocks/auto/28/62/51/06_fan-naruto.ru.png

_Колония для Одиночек_
Томы/главы - /vol1/0
Страницы - всего одна страница, клик скроллит:
- https://h24.mangas.rocks/auto/11/61/31/01.png_res.jpg?t=1622074233&u=0&h=kNXL-sVaqwe5Owwf7zlkNg
- https://h40.mangas.rocks/auto/11/61/31/02.png_res.jpg?t=1622074233&u=0&h=vdMlGHveC-FjuHAxJ7TQdA

_Поднятие уровня в одиночку_
Томы/главы - /vol1/0
Страницы - #page=2:
- https://h8.mangas.rocks/auto/27/52/00/001.jpg_res.jpg?t=1622062065&u=0&h=ZjiH0g_luhGr5WclIdVopg
- https://h42.mangas.rocks/auto/27/52/00/002.jpg_res.jpg?t=1622062065&u=0&h=rhepflNK-WB0jL16n6ldiA
- https://h38.mangas.rocks/auto/27/52/00/003.jpg_res.jpg?t=1622062065&u=0&h=GhJF4wRJPv231Ipl54JTXQ
- https://h37.mangas.rocks/auto/27/52/00/004.jpg_res.jpg?t=1622062065&u=0&h=EHKOkZ3ShFiHkjRt8ZSv7g

По итогу получается, что есть несколько (возможно ~50) статик серверов. Скорее всего, юзается в основном только ~15,  но это не точно. Так же глава может быть доступна на >1 из серверов, но не всегда и не на всех

------

Если ссылка на главу **не динамическая**, то грузим её on demand и кешируем в БД.
Подгружать можно 2 способами:
1. Через _GET_ на главу + и парсить html. Таким образом за 1 запрос можно получить точно все картинки главы
2. Параллельные запросы на все статик серверы и берем ссылку у того, кто первый ответит. Этот вариант выглядит похуже тк:
    1. Не обязательно стабилен, мы не знаем, что за сервера есть
    2. Какой-то ддос, не этично

Зато второй вариант избегает серверсайд запроса и уменьшает возможность получить 429 + может увеличить задержку при большой нагрузке

Если ссылка **динамическая**, то всё плохо и кеширование будет менее эффективным
