### ISSUE TITLE
Парсинг глав

### ISSUE THREAD

**Issue by dhvcc** [Sora-reader/backend#54]
Нужно добавить логику + management команду для парсинга списка глав (`./manage.py parse-chapters ID_из_бд`)

Парсить нужно RSS, по ссылке `https://readmanga.live/rss/manga?name=...`

Ссылку эту нужно брать из Филда `rss_link`

Это отдельная логика от парсинга деталей, однако, скорее всего, будет так же использоваться в DetailView API

Скорее всего подойдёт [моя либа](https://github.com/dhvcc/rss-parser)

Как плюс, но не обязтельно - кешировать это всё в редисе на 1ч

**Comment by NikDark** [comment]
Скорее всего надо добавить, чтобы в модели хранилась ссылка на RSS, потому что я нашел несколько манг, в которых отличается name и RSS-name
Example:
https://readmanga.live/naruto__A1ec180
https://readmanga.live/rss/manga?name=naruto

**Comment by NikDark** [comment]
blocked #50
