### ISSUE TITLE
Парсинг изображений

### ISSUE THREAD

**Issue by NikDark** [Sora-reader/backend#69]
Нужно написать management-command для парсинга картинок. 
Команда вызывает отдельную функцию, которая парсит картинки.
Получение ссылок на картинки для глав происходит on-demand, через парсинг. Ссылки кешируются на 1 час (можно для этого использовать редис)
ссылки на картинки `./manage.py parse-images {ID_из_бд} {vol_№} {chapter_№}`

**Comment by NikDark** [comment]
Нужно обсудить как будем хранить картинки
И будем ли мы их вообще хранить в БД или только в Redis

**Comment by dhvcc** [comment]
Я думал по этому поводу и пришёл к выводу, что, наверное, лучше в режиме
Наши картинки привязаны к токенам, которые не вечны (~8ч), так что, думаю пока можно и а редис.
Нагрузка не такая большая, но стоит посмотреть будет ли хватать памяти редиса

**Comment by dhvcc** [comment]
Памяти должно определённо хватить, даже если используем 15мб от хероку
```
localhost:8883> SET chapter https://readmanga.live/bashnia_boga/vol3/72
OK
localhost:8883> DEBUG OBJECT chapter
Value at:0x7f3eda741e80 refcount:1 encoding:embstr serializedlength:44 lru:14262809 lru_seconds_idle:7
localhost:8883> MEMORY USAGE chapter
(integer) 101
```

**Comment by NikDark** [comment]
Может на всякий случай добавить парсер целого volume? Аргумент chapter сделать опциональным
