### ISSUE TITLE
Убрать автогенерацию сваггера

### ISSUE THREAD

**Issue by dhvcc** [Sora-reader/backend#78]
АПИ готово, схема завершена для MVP
Пора убрать `drf_spectacular` и раздавать схему из своих файлов
Но для начала нужно проверить, есть ли другой более удобный способ делать вью для сваггера и редока
То есть

1. Перенести схему в статик файлы
2. Проверить, можно ли заменить раздачу сваггера `drf_spectacular` 
3. Убрать по возможности `drf_spectacular`
4. Если убрали, то найти замену для раздачи `SwaggerUI/Redoc` на `/ap/docs/...` (которые должны использовать нашу кастомную схему)

**Comment by NikDark** [comment]
Ахахахахах
Тебе Леша с таким описанием issue надо писать диалоги к варкрафту :laughing: 
Наш рудник почти исчерпан, нужно больно зигурат !

**Comment by NikDark** [comment]
Есть вариант убрать `drf_spectacular`, но для этого метода всегду должен быть интернет или установлена зависимость в `npm`
Но так как это и так будет на сервере, а к серверу нужен доступ через инет, поэтому можно сделать и так наверное

**Comment by dhvcc** [comment]
> Есть вариант убрать `drf_spectacular`, но для этого метода всегду должен быть интернет или установлена зависимость в `npm`
> Но так как это и так будет на сервере, а к серверу нужен доступ через инет, поэтому можно сделать и так наверное

Ну раз так, то можно, наверное, оставить его
Просто убрать упоминания о генерации в схемах и оставить только вьюхи
