### ISSUE TITLE
[RESEARCH] Sentry 

### ISSUE THREAD

**Issue by dhvcc** [Sora-reader/backend#79]
Очевидно, нужно подключить Sentry
Только вопрос в том:

1. Как менеджить права
2. Можно сделать публичную оргу? Бесплатно офк
3. Если не получится, то можно ли удобно развернуть локальный сентри из композа? Как?

**Comment by zym43210** [comment]
![image](https://user-images.githubusercontent.com/54810126/124286491-b0378b80-db57-11eb-9489-97a03bcc36fe.png)

**Comment by dhvcc** [comment]
@zym43210 а можно ли организацию зарегать, нужно ли паблик делать, как менеджить права
Там же не один пункт вопросов

**Comment by NikDark** [comment]
В сентри любой аккаунт является организацией, но чтобы добавить юзеров, обычный план не подойдет, нужно как минимум план Team за 26$
Можно сделать self-hosted sentry
И я посмотрел, развернул у себя на машине и в self-hosted доступны вроде бы все фичи. Так что предлагаю организовать как-то self-hosted sentry. И это выйдет дешевле, чем покупать подписку на sentry

**Comment by NikDark** [comment]
Пробуем использовать GlitchTip
Это легковесный Sentry, который можно поднять на бесплатном хероку
