### ISSUE TITLE
Запоминание позиции в лист вью

### ISSUE THREAD

**Issue by dhvcc** [Sora-reader/backend#92]
Нужно, что бы АПИ отдавало мангу в таком же порядке, в каком она на лист вью источника, так как там всегда отсортировано по популярности

То есть, если Solo Levelling на ReadManga первее всех манг, то и при поиске нужно отдавать его первым

Нужно добавить филд, по типу `popularity` `IntegerField`

**Comment by NikDark** [comment]
Так может сортировать выдачу поиска по `rating`?

**Comment by dhvcc** [comment]
> Так может сортировать выдачу поиска по `rating`?

У манги, которую читают 2.5 человека может быть рейтинг 4.9
Поэтому не подойдёт такая метрика
