### ISSUE TITLE
EC2 deploy

### ISSUE THREAD

**Issue by dhvcc** [Sora-reader/backend#95]
Надо настроить развертывание на EC2 и добавить соответствующие `github-actions` для деплоя каждого коммита в `develop`

Надо с композом поднимать бд, редис и все остальное + написать restart policy если в композе ещё нет

При передеплой нужно обновлять только веб

**Comment by NikDark** [comment]
1. Склонить репу на сервак.
2. Написать restart policy
3. Развернуть композ
4. Написать Github Action для autodeploy

**Comment by dhvcc** [comment]
@NikDark у меня сейчас больше времени появилось, так что я возьму этот тикет, если ты не против

**Comment by dhvcc** [comment]
Добавлено в 9756a658204c7f31a4a78d9d9aae7283cdf032cd
